FROM python:3.10-slim

# Install FFmpeg system dependency
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5000 and run via Gunicorn instead of standard development flask
RUN pip install gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:5000", "server:app"]